spring.application.name=proyecto3
server.port = 2006

spring.mongodb.uri=mongodb+srv://ayme_mario_db:_Lu1s2o06@mario.dt0ntxv.mongodb.net/tienda_db?appName=Mario

app.admin.email=mario_admin@smartphonesstore.com
app.admin.password=_Lu1s2o06

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB